sachaos/todoist

- .gitignore
- lib/todoist.go
- main.go
- quick.go
Todoist has a way to allow the user to send a string and have it parsed similar to how it would be in the UI. This adds a command to the cli for it.
> Added quick command to add tasks as if they were entered in the todoist UI

- lib/todoist.go
The original implementation was incorrect due to a misunderstanding on
how sort.Search works as the list needs to be already sorted. This would
cause it to fail to find an existing match under certain scenarios.
Change to use range search instead.
> Change to use range instead of sort.Search for prefix matching.

- README.md
- main.go
I thought it would be a little cleaner if the verb tense were standardized in the imperative. Right now it's a mix of imperative and... descriptive (forget what that tense is called).
> Standardize verb tense in help

- filter_eval_test.go
- lib/item.go
The root cause of the bug is that Todoist returns `null` for the `due_date_utc`
field when no due date is set. Go's json decoder simply ignores null values,
so the DueDateUtc field wasn't being set correctly.
It was fixed by making DueDateUtc a string pointer. Go's json decoder does set
a string pointer to `nil` if the json value is `null`.
This should fix #68.
> Fix broken due dates

- main.go
Currently, colorized output is not working correctly on Windows. This change uses `runtime.GOOS` to detect the OS type and switch the output to `color.Output` for Windows (if `--color` is specified).
>  Correctly show colorized output on Windows

- Dockerfile
This PR fixes #101 which refers to an issue with `go get` in the Dockerfile. Instead of using `go get`, I follow the procedure mentioned in the readme. I first clone the git repository and then run `go install`.
> Fix issue with 'go get' in Dockerfile

- main.go
This PR addresses issue #102.
I set file permissions 0600 for config file when being created and check the permissions in each execution of the script.
**Attention**: This would be a breaking change for all those that have already created a config file which now has not permissions 0600.
> File permissions of config file

- lib/item.go
- show.go
Hi, thanks for the nice CLI tool. This pull request is intended to address the following points.
- Fix the incorrect match of regex, when multiple URLs exist within a task (apply non-greedy match).
- Change the behavior of `GetContentURL` to return the URL itself, and also allows to extract multiple URLs.
For a following task string,
`Read [Todoist - Key Features](https://get.todoist.help/hc/en-us/categories/115000632125) and [Todoist - FAQ & Troubleshooting](https://get.todoist.help/hc/en-us/categories/115000626249)`
change the behavior as follows.
**Before**
```
$ todoist show 3629294999
ID       3629294999
Content  Read Todoist - Key Features](https://get.todoist.help/hc/en-us/categories/115000632125) and [Todoist - FAQ & Troubleshooting
Project  #Inbox
Labels
Priority p4
DueDate
URL …
```
> Fix for url parsing in task content

- lib/item.go
This fixes #106, the issue that it wasn't parsing dates with a timezone from Todoist properly datetimes with a floating timezone were retrieved like `2020-01-13T19:23:11` whereas datetimess with a timezone (which the CLI creates automatically) uses the format `2020-01-13T19:23:11Z` which the existing parser did not support
> Fix parsing dates with timezones

- README.md
I added location of the API token that needs to be pasted into the todoist. It makes the installation process easier when you don't need to search for it. :wink:
> Add getting token description

- README.md
The documentation example mentions filtering by priority with `!p1`.
This used to be the case, but Todoist has dropped the exclamation mark a while ago for this filter.
`./todoist list -f '(overdue | today) & !p1'` also shoes other priorities than `p1`.
`./todoist list -f '(overdue | today) & p1'` filters correctly.
> Fixed documentation on Todoist filtering syntax

- todoist_functions_fzf_bash.sh
Hi @sachaos, thanks for creating this project. 🙂 
Your current completion scripts only work with zsh (maybe they should have a `.zsh` extension instead?).
I created this Bash completion script (for fzf only) as a suggestion.
Comments:
- As far as I understood, the zsh scripts work with key bindings to show the list of labels and projects.
This Bash script will complete labels and projects when TAB is pressed after `--label-ids`, `--project-id` or `--project-name`.
- I didn't add instructions to the [README on how to install with Homebrew](https://github.com/sachaos/todoist#if-installed-via-homebrew), because I don't know how you will pack this file into your tap.
- ~~I didn't implement task selection yet (`select_items_command` in your scripts), because I didn't understand/investigate/try …
> Add bash completion with fzf

- Dockerfile
Prior to this PR, I get the following error upon entering the docker container:
```ps1
PS C:\Users\felix> todoist
bash-5.0# todoist
panic: Config file has wrong permissions. Make sure to give permissions 600 to file /root/.todoist.config.json
goroutine 1 [running]:
main.main.func1(0xc0000d2840, 0xc0000d2800, 0xe)
/go/src/github.com/sachaos/todoist/main.go:152 +0xb68
github.com/urfave/cli.(*App).Run(0xc00009f380, 0xc0000a6020, 0x2, 0x2, 0x0, 0x0)
/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:241 +0x7bd
main.main()
/go/src/github.com/sachaos/todoist/main.go:290 +0x17eb
```
> Set permissions of .todoist.config.json to 600 in Dockerfile

- README.md
- main.go
It is possible to add some autocompletion to the shell by setting the `app.EnableBashCompletion = true` flag.
https://github.com/urfave/cli/blob/master/docs/v1/manual.md#bash-completion
This autocompletes subcommands automatically.
This seems to have picked up a bunch of short alias commands too, so that might need tidying up.
It would also be nice in the future to add custom handlers which would for autocompleting things like `todoist delete <task id>` where a list of tasks would be shown.
I just wanted to raise this to get the ball rolling on adding autocompletion.
Related to #126
> Start on shell completion

- cache.go
- main.go
This will close #118 
This will use cache from `~/.cache/todoist/cache.json` (or if you have `XDG_CACHE_HOME` then in your path)
> Move cache to .cache

- main.go
This makes help messages more useful. e.g. `todoist close --help` now shows `USAGE: todoist close <Item ID>` instead of `USAGE: todoist close [arguments...]`.
> Specify ArgsUsage for all commands

- format.go
- lib/interface.go
- lib/item.go
- lib/section.go
- lib/sync.go
- list.go
Section can be used as subproject in Todoist. So section field is added in cache file and also section name will be displayed after project name when using "list" command just like how the Todoist web application is doing. 
Adding/deleting sections feature will be added later.
> support section name displaying in list command

- main.go
I'm not a Go developer, but I looked at the other open PR for this issue and it seems too complicated. All I'm doing here is adding an additional condition to `if` statement that avoids checking for a value of `0600` if the currently running OS is Windows. If you want to implement a different solution for this, feel free to close the PR.
> Remove config perm check for Windows

- main.go
- utils.go
Hey sachaos, first of all thanks a lot for this tool, it is already of great use to me!
I propose a change to allow users to set configuration values (especially the API token) via environment variables. Depending on one's personal setup, this makes it much easier to inject secrets from password stores/vaults instead of storing them in the `.config` directory.
The library `viper` which is used to manage the app's config already supports environment variables, which makes it much easier to implement this change. I additionally tried to keep the existing logic for initializing the config file interactively if it hasn't been found on disk.
My code is still rough on the edges, but i wanted to ask you first if there is any interest in this change before cleaning it up. I also have to admit …
> Allow setting config values via environment variables

- lib/sync.go
This should fix #214 with the boolean type in the struct of reminder sync.
> fixes bool/int error message for unmarshaling struct

- main.go
Updated the Before call to check if the configured token matches the cached token. If it doesn't, resync and reload the cache before performing the requested operation
> fix(main.go): resync if cached token is not equal to the configured token

- add.go
- lib/item.go
- modify.go
Changed [lib/item.go](https://github.com/sachaos/todoist/blob/master/lib/item.go) to send [Due struct](https://github.com/sachaos/todoist/blob/b057a90ebcbaa28788e136795ebd385b68b8b5af/lib/item.go#L20-L26) in [params ](https://github.com/sachaos/todoist/blob/b057a90ebcbaa28788e136795ebd385b68b8b5af/lib/item.go#L153-L198)for adding and updating tasks. Changed `add.go` and `modify.go` to create a Due struct and add said Due struct to Item struct instead of setting `item.Datestring`. This change is due to an API change by Todoist.
I did have to bring the library into `modify.go` so I could create the Due struct. It was already referenced for other purposes in `add.go`
There may be a better way to do this, it seems a bit messy to me, so I'm (always) open to feedback.
> fix(issue-#216): resolves modifying and setting date on task creation

- add_project.go
Updated add project to check if color doesn't exist, to elimiate the issues of passing `0` to the api, which is causing an issue. Resolves issue #244
> Added check for project color non-existant

- add.go
See #252 for details of `--project-name`.  This change causes `--project-name` to be preferred over `--project-id` whenever specified. An error will be reported if a project with that name cannot be found.
For the error about exactly one positional argument, there might be a nice alternative to instead intersperse the arguments with " ".  To me the `todoist add --help` suggests that this should be possible:
>    todoist add [command options] <Item content>
Instead, this just complains when there are positional arguments that are unused by the current logic.
> Fix "add --project-name" and check for exactly one positional argument

- README.md
The current README suggests using `brew install todoist`, which defaults to installing the cask (GUI application) rather than the formula (CLI tool). This can cause confusion for users looking to install the CLI tool.
This PR updates the installation instructions in the README to explicitly specify the correct command for the CLI tool:
- Use `brew install sachaos/todoist/todoist` for the CLI tool.
> Fix README brew install command for Todoist CLI to avoid cask-formula conflict

- .goreleaser.yml
The autocomplete files are missing from the released archives. This causes a failure in the brew install/updates:
Error: An exception occurred within a child process:
Errno::ENOENT: No such file or directory - todoist_functions.sh
Although todoist_functions_fzf_bash.sh is not needed, added for completeness for those using Bash.
> Add autocomplete files to archives
