sachaos/todoist

- README.md
- lib/sync.go
- main.go
Modify LiveNotification SeqNo type to int64
#2
> Fix bug #2

- todoist_functions.sh
https://github.com/sachaos/todoist/issues/5
> Fix gnu date is incompatible with bsd date issue

- format.go
- lib/sync.go
Fix https://github.com/sachaos/todoist/issues/7
Accept task which has unknown project ID, and display it as `Unknown` project.
> Accept unknown project ID

- main.go
> Padding month and day by zero

- README.md
- main.go
- modify.go
- show.go
> Remove harsh error on nonexistent task id

- completed.go
- filter_eval.go
- filter_parser.y
- filter_parser_test.go
- lib/item.go
- list.go
- main.go
- show.go
Improvements for https://github.com/sachaos/todoist/issues/29
I created some abstractions: unified DateTime and EvalDate methods, AbstractItem interface. Please, review the changes and inform me, if I not following project conventions.
Also, please check the https://github.com/sachaos/todoist/issues/30. I cannot write new tests because test suite not working.
> Add shortcut and filters for `completed-list`

- filter_eval_test.go
- filter_parser.y
- filter_parser_test.go
Fix https://github.com/sachaos/todoist/issues/30
> Modify test bug

- add.go
- delete.go
- lib/interface.go
- lib/project.go
- lib/todoist.go
- main.go
- modify.go
Just started using todoist CLI today and these are 2 minor things that were causing me a bit of pain so I went ahead and added them.
Big Disclaimer: I am not a golang programmer, so some or all of this may not be the idiomatic Go way of doing things. It might also break some encapsulation or otherwise that you were hoping to maintain. But I've tested both changes and they work for me.
> Support for specifying project by name, and todo IDs by unique prefix

- filter_parser.y
Fix for https://github.com/sachaos/todoist/issues/37
I just added more informative error message for this cases
> Add more accurate error message for filter errors

- add.go
- lib/item.go
- main.go
I want to set a reminder automatically when add task. so I added this option.
> Added option that set reminder when add task

- README.md
> Update README for issue #28

- README.md
- lib/todoist.go
- main.go
fix for https://github.com/sachaos/todoist/issues/43
> Add 'color' config option

- completed.go
- filter_eval.go
- filter_eval_test.go
- filter_parser.y
- filter_parser_test.go
- lib/item.go
- lib/project.go
- list.go
It is same attribute with https://get.todoist.help/hc/en-us/articles/205248842-Filters
> Implement project filter

- Dockerfile
- Makefile
- README.md
This PR is for the ones (as me) that don't like to install libs running make, because updates for this kind of installation can be really messy sometimes.
PS: Thanks for this cli!
> Add Docker as Install mode.

- README.md
- go.mod
- go.sum
- main.go
os.UserHomeDir() was included in golang 1.12, so I switched from mitchellh/go-homedir.
> drop mitchellh/go-homedir dependency

- snap/snapcraft.yaml
This is a simple file to build a snap (see https://snapcraft.io or @snapcore for more information).  In theory, the only maintenance that this will need going forward is updating the version string.  Feel free to update the other meta-data to better reflect what you feel it should be.
If you would like, then this can be registered with snapcraft.io to automatically be uploaded to their repo whenever you tag a new release. @wimpysworld might be able to help you if you would like.
Thanks for creating and publishing this!
> Adding snapcraft.yaml file for snapd support

- README.md
- add.go
- cache.go
- completed.go
- filter_eval.go
- filter_eval_test.go
- format.go
- lib/interface.go
- lib/item.go
- lib/main.go
- lib/project.go
- lib/sync.go
- lib/todoist.go
- list.go
- main.go
- modify.go
- projects.go
- show.go
> Use Todoist API v8

- list.go
> Add more confortable error message

- add.go
- close.go
- completed.go
- delete.go
- filter_eval.go
- lib/project.go
- list.go
- modify.go
- sync.go
multiple small changes to improve readability and performance (due to better slice appending in commit 
57d3767)
> code quality improvements

- main.go
Now month and day field can be distinguished based on the number. I also updated the year to the current one because why not :smile:, but I can change it back if you have some sentiment to it :open_mouth:
> Update example dates

- add_project.go
- lib/project.go
- main.go
As in #113 I added command for adding new project.
You can specify project color with `--color` and order in project list with `--item-order`
> Add project

- README.md
Please only merge after https://github.com/sachaos/homebrew-todoist/pull/9/.
> Update keybind install documentation for homebrew users

- cache.go
- main.go
- utils.go
As in #119 I also moved config file to $XDG_CONFIG_HOME. This will close #23
> Move config to .config

- README.md
- cache.go
- go.mod
- go.sum
- main.go
- sync.go
In this PR I cleaned up a little config and cache file loading.
> Use xdg/basedir

- Dockerfile
> Fix wrong config path on Dockerfile

- README.md
This PR only adds more information at the NixOS installation to fix #165
> Giving more information about NixOS installation on README.md

- add.go
- add_project.go
- cache.go
- close.go
- completed.go
- delete.go
- filter_eval.go
- filter_eval_test.go
- format.go
- lib/interface.go
- lib/item.go
- lib/label.go
- lib/main.go
- lib/project.go
- lib/sync.go
- lib/todoist.go
- lib/user.go
- list.go
- main.go
- modify.go
- projects.go
- show.go
- utils.go
Hey, I did the migration to v9 following the [migration guide](https://developer.todoist.com/sync/v9/#migrating-from-v8)
There are a lot of changes, but the commits should be small enough for easier review.
I have still a problem with the add-project command (which returns 200 from the API but doesn't add a project) otherwise it looks fine
Fixes #196
> Migrate to v9

- main.go
> fix(main.go): updated config/cli check to set color.NoColor to false

- README.md
Wrote fish fzf functions with similar functionalities as here: https://github.com/sachaos/todoist/blob/master/todoist_functions_fzf.sh
> Add repository with fish fzf support

- Makefile
Added `.exe` to the Windows build. Also added a build target for Apple Silicon Macs (darwin arm64)
> fix(makefile): update makefile to resolve #158 

- .github/workflows/release.yml
- .goreleaser.yml
- main.go
Add CI workflow to release automatically.
> Enable to release by CI
